#ifndef __ID_HPP_
#define __ID_HPP_

// define all id's for paint program here so none conflict

enum { 
  PAINT_CLOSE_TITLE=2,
  PAINT_NEW_IMAGE,
  PAINT_NEW_BACKTILE,
  PAINT_NEW_FORETILE,
  PAINT_NEW_W,
  PAINT_NEW_H,
  PAINT_NEW_NAME,
  PAINT_OK_POINTS,
  PAINT_FINISH_POINTS,
  PAINT_NEW_CHARACTER,
  PAINT_ANIMATE_CLEAR,
  PAINT_ANIMATE,
  PAINT_ANIMATE_DONE,
  PAINT_ANIMATE_SPEED_UP,
  PAINT_ANIMATE_SLOW_DOWN,
  PAINT_ANIMATE_FORWARD,
  PAINT_ANIMATE_BACKWARD,

  PALETTE_EDIT_COLOR,

  ITEM_OK,
  ITEM_CANCEL,
  FORETILE_EDIT_POINTS,
  FORETILE_SHOW_POINTS,
  FORETILE_HIDE_POINTS,
  FIGURE_EDIT_HIT,
  FIGURE_EDIT_DAMAGE,
  FIGURE_EDIT_TOUCH,
  FIGURE_SHOW_HIT,
  FIGURE_SHOW_DAMAGE,
  FIGURE_SHOW_TOUCH,
  FIGURE_HIDE_HIT,
  FIGURE_HIDE_DAMAGE,
  FIGURE_HIDE_TOUCH,
  FIGURE_EDIT_XCENTER,
  FIGURE_SHOW_XCENTER,
  FIGURE_HIDE_XCENTER,

  ITEM_W,
  ITEM_H,
  ITEM_NAME,
  ITEM_NEXT,
  ITEM_DAMAGE,
  FIGURE_DAMAGE,
  FIGURE_ADVANCE,
  MODE_BUTTON_BOX,

  MODE_PIXEL_DRAW,
  MODE_IMAGE_DRAW,
  MODE_ZOOM_IN,
  MODE_ZOOM_OUT,
  MODE_FILL,
  MODE_AREA_SELECT,
  MODE_POLY_SELECT,
  MODE_LINE,
  MODE_CIRCLE,
  MODE_RECT,
  MODE_BAR,
  MODE_TILE,
  INDEX_PICK,
  EDIT_MODE,


  AREA_SELECT,
  WAIT_KEY,
  ANIMATING,
  LINE_SELECT,
  CIRCLE_SELECT,
  RECT_SELECT,
  ANIMATE_PICK,
  POINT_SELECT_START,
  POINT_SELECT,
  POINT_SELECT_XCENTER,
  POINT_SELECT_XCENTER_START,
  ANIMATE_START,
  ANIMATE_FINISH,
  MOUSE_STATE_CHANGE,
  SAT_R,
  SAT_G,
  SAT_B,

  PCMD_DIAG_FIRST,
  PCOMMAND_FIRST=PCMD_DIAG_FIRST+30,
  PCOMMAND_OK=PCOMMAND_FIRST+100,
  PCOMMAND_CANCEL,
  LAST_ID,
} ;

#define FIRST_MODE MODE_PIXEL_DRAW
#define LAST_MODE EDIT_MODE

#endif




